In [31]:
from datetime import datetime
from datetime import timedelta
import numpy as np
import pandas as pd

data = pd.read_csv('useful_no_solar/run_household_{}/power2016Household.csv'.format(1), usecols=[2])
data.rename({'Power consumed': 'PowerConsumed'}, inplace=True)
base = datetime(2016, 1, 1)
dt = [base + timedelta(minutes=x) for x in range(len(data))]
data['date'] = dt
data = data.set_index('date')

In [32]:
data

                     Power consumed
date
2016-01-01 00:00:00        0.417449
2016-01-01 00:01:00        0.417449
2016-01-01 00:02:00        0.417449
2016-01-01 00:03:00        0.417449
2016-01-01 00:04:00        0.417449
2016-01-01 00:05:00        0.417449
2016-01-01 00:06:00        0.417449
2016-01-01 00:07:00        0.000000
2016-01-01 00:08:00        0.000000
2016-01-01 00:09:00        0.000000
2016-01-01 00:10:00        0.000000
2016-01-01 00:11:00        0.000000
2016-01-01 00:12:00        0.000000
2016-01-01 00:13:00        0.000000
2016-01-01 00:14:00        0.000000
2016-01-01 00:15:00        0.000000
2016-01-01 00:16:00        0.000000
2016-01-01 00:17:00        0.000000
2016-01-01 00:18:00        0.000000
2016-01-01 00:19:00        0.000000
2016-01-01 00:20:00        0.000000
2016-01-01 00:21:00        0.000000
2016-01-01 00:22:00        0.000000
2016-01-01 00:23:00        0.000000
2016-01-01 00:24:00        0.101516
2016-01-01 00:25:00        0.101516
2016-01-01 00:26:00        0.101516
2016-01-01 00:27:00        0.101516
2016-01-01 00:28:00        0.101516
2016-01-01 00:29:00        0.101516
...                             ...
2016-12-31 23:30:00        0.526922
2016-12-31 23:31:00        0.526922
2016-12-31 23:32:00        0.526922
2016-12-31 23:33:00        0.417449
2016-12-31 23:34:00        0.417449
2016-12-31 23:35:00        0.417449
2016-12-31 23:36:00        0.000000
2016-12-31 23:37:00        0.000000
2016-12-31 23:38:00        0.000000
2016-12-31 23:39:00        0.000000
2016-12-31 23:40:00        0.000000
2016-12-31 23:41:00        0.000000
2016-12-31 23:42:00        0.000000
2016-12-31 23:43:00        0.000000
2016-12-31 23:44:00        0.000000
2016-12-31 23:45:00        0.000000
2016-12-31 23:46:00        0.000000
2016-12-31 23:47:00        0.000000
2016-12-31 23:48:00        0.000000
2016-12-31 23:49:00        0.000000
2016-12-31 23:50:00        0.000000
2016-12-31 23:51:00        0.000000
2016-12-31 23:52:00        0.000000
2016-12-31 23:53:00        0.000000
2016-12-31 23:54:00        0.101516
2016-12-31 23:55:00        0.101516
2016-12-31 23:56:00        0.101516
2016-12-31 23:57:00        0.101516
2016-12-31 23:58:00        0.101516
2016-12-31 23:59:00        0.101516

[527040 rows x 1 columns]

In [28]:
data[-10:].to_json()

'{"Power consumed":{"1483228200000":0.0,"1483228260000":0.0,"1483228320000":0.0,"1483228380000":0.0,"1483228440000":0.101516,"1483228500000":0.101516,"1483228560000":0.101516,"1483228620000":0.101516,"1483228680000":0.101516,"1483228740000":0.101516}}'